name: Main Workflow

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: "eu-west-1" # optional: defaults to us-east-1

defaults:
    run:
        shell: bash


jobs:
    landing:
        name: Build and Deploy Landing Page
        runs-on: ubuntu-latest
        env:
            NAME: "landing"
        defaults:
            run:
                working-directory: "./$NAME"
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build -- --base=/

            - name: Deploy to AWS S3
              uses: jakejarvis/s3-sync-action@master
              with:
                args: --acl public-read --follow-symlinks --delete


    clicker:
        name: Build and Deploy Clicker Game
        runs-on: ubuntu-latest
        env:
            NAME: "simple-clicker"
        defaults:
            run:
                working-directory: "./$NAME"
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build -- --base=/$NAME/

            - name: Deploy to AWS S3
              uses: jakejarvis/s3-sync-action@master
              with:
                args: --acl public-read --follow-symlinks --delete
              env:
                DEST_DIR: $NAME

    # coin-clicker:
    #     needs: clicker
    #     uses: ./.github/workflows/coin-clicker.yml

    # memory-circles:
    #     needs: coin-clicker
    #     uses: ./.github/workflows/memory-circles.yml

    # pong:
    #     needs: memory-circles
    #     uses: ./.github/workflows/pong.yml