name: Main Workflow

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

defaults:
    run:
        shell: bash


jobs:
    landing:
        name: Build and Deploy Landing Page
        runs-on: ubuntu-latest
        environment: production
        env:
            NAME: "landing"
        defaults:
            run:
                working-directory: "./landing"
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build -- --base=/

            - name: Deploy to AWS S3
              uses: jakejarvis/s3-sync-action@master
              with:
                args: --acl public-read --follow-symlinks --delete
              env:
                AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: "eu-west-1" # optional: defaults to us-east-1
                SOURCE_DIR: "./$NAME/dist"
                DEST_DIR: ""

    simple-clicker:
        needs: landing
        environment: production
        name: Build and Deploy Simple Clicker Game
        runs-on: ubuntu-latest
        env:
            NAME: "simple-clicker"
        defaults:
            run:
                working-directory: "./simple-clicker" # does not work with variables
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Install dependencies
              run: npm ci

            - name: Build project
              run: npm run build -- --base=/$NAME/

            - name: Deploy to AWS S3
              uses: jakejarvis/s3-sync-action@master
              with:
                args: --acl public-read --follow-symlinks --delete
              env:
                AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                SOURCE_DIR: "./$NAME/dist"
                DEST_DIR: $NAME

    coin-clicker:
        needs: landing
        environment: production
        name: Build and Deploy Coin Clicker Game
        runs-on: ubuntu-latest
        env:
            NAME: "coin-clicker"
        defaults:
            run:
                working-directory: "./coin-clicker" # does not work with variables
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "20.x"

        - name: Install dependencies
          run: npm ci

        - name: Build project
          run: npm run build -- --base=/$NAME/

        - name: Deploy to AWS S3
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            SOURCE_DIR: "./$NAME/dist"
            DEST_DIR: $NAME

    memory:
        needs: landing
        environment: production
        name: Build and Deploy Memory Game
        runs-on: ubuntu-latest
        env:
            NAME: "memory"
        defaults:
            run:
                working-directory: "./memory" # does not work with variables
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "20.x"

        - name: Install dependencies
          run: npm ci

        - name: Build project
          run: npm run build -- --base=/$NAME/

        - name: Deploy to AWS S3
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            SOURCE_DIR: "./$NAME/dist"
            DEST_DIR: $NAME

    pong:
        needs: landing
        environment: production
        name: Build and Deploy Pong Game
        runs-on: ubuntu-latest
        env:
            NAME: "pong"
        defaults:
            run:
                working-directory: "./pong" # does not work with variables
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "20.x"

        - name: Install dependencies
          run: npm ci

        - name: Build project
          run: npm run build -- --base=/$NAME/

        - name: Deploy to AWS S3
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            SOURCE_DIR: "./$NAME/dist"
            DEST_DIR: $NAME
        